version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/TicketsBot/translationgenerator

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Build i18n platform
          command: go build -o i18n cmd/translationgenerator/main.go

      - run:
          name: Build importer
          command: go build -o importer cmd/import/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/translationgenerator/i18n
          destination: i18n

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/translationgenerator/importer
          destination: importer